title:            Statistical Genetics Laboratory
description:      Research group that studies the genetic architecture of quantitative traits 
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://statgen-esalq.github.io/

# Owner/author information
owner:
  name:           Department of Genetics
  avatar:         LogoLabAvatar.png
  bio:            "ESALQ/USP"
  email:          aafgarci@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: aafgarci       
  facebook: groups/611026095639818/      
  github: statgen-esalq/statgen-esalq.github.io         
  stackoverflow: 
  linkedin: http://www.linkedin.com/groups/Statistical-Genetics-Laboratory-8124864/about
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/u/0/communities/103592582757513673768

# Analytics and webmaster tools stuff goes here
google_analytics: UA-51935714-1  
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
#  - title: Theme Setup
#    url: /theme-setup/
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true
  - title: People
    url: /people/
  - title: Former Students
    url: /former-students/
#  - title: Genetics, ESALQ/USP
#    url: http://www.genetica.esalq.usp.br/
#    external: true
  - title: Softwares
    url: /softwares/
  - title: Contact
    url: /contact/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
pygments:    true
markdown:    kramdown
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
